### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by royaalto** [pgigioli/darknet_ros#10]
Hi, I clone your code ,and catkin_make, get this error, I use ubuntu16.04 and cuda9.0 , kinetics, what can i do?

-- Using CATKIN_DEVEL_PREFIX: /home/roy/catkin_ws/devel
-- Using CMAKE_PREFIX_PATH: /home/roy/catkin_ws/devel;/opt/ros/kinetic
-- This workspace overlays: /home/roy/catkin_ws/devel;/opt/ros/kinetic
-- Using PYTHON_EXECUTABLE: /usr/bin/python
-- Using Debian Python package layout
-- Using empy: /usr/bin/empy
-- Using CATKIN_ENABLE_TESTING: ON
-- Call enable_testing()
-- Using CATKIN_TEST_RESULTS_DIR: /home/roy/catkin_ws/build/test_results
-- Found gtest sources under '/usr/src/gtest': gtests will be built
-- Using Python nosetests: /usr/bin/nosetests-2.7
-- catkin 0.7.6
-- BUILD_SHARED_LIBS is on
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- ~~  traversing 2 packages in topological order:
-- ~~  - darknet_ros
-- ~~  - usb_cam
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- +++ processing catkin package: 'darknet_ros'
-- ==> add_subdirectory(darknet_ros)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
-- darknet_ros: 2 messages, 0 services
-- +++ processing catkin package: 'usb_cam'
-- ==> add_subdirectory(usb_cam)
-- Configuring done
CMake Error at /usr/share/cmake-3.5/Modules/FindCUDA.cmake:1693 (add_executable):
  Cannot find source file:

    darknet/src/activation_layer.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx
Call Stack (most recent call first):
  darknet_ros/CMakeLists.txt:124 (cuda_add_executable)

CMake Warning (dev) at darknet_ros/CMakeLists.txt:153 (add_dependencies):
  Policy CMP0046 is not set: Error on non-existent dependency in
  add_dependencies.  Run "cmake --help-policy CMP0046" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  The dependency target "my_package_generate_messages_cpp" of target
  "yolo_ros" does not exist.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at darknet_ros/CMakeLists.txt:152 (add_dependencies):
  Policy CMP0046 is not set: Error on non-existent dependency in
  add_dependencies.  Run "cmake --help-policy CMP0046" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  The dependency target "my_package_generate_messages_cpp" of target
  "single_image_test" does not exist.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
-- Build files have been written to: /home/roy/catkin_ws/build
Invoking "cmake" failed

**Comment by HankerSia** [comment]
you need use the cuda 8.0, i remember darknet did not support cudn 9.0, i have tried it before

**Comment by pgigioli** [comment]
Did you clone the repo with --recursive? Looks like its unable to find the C file from the darknet submodule.  reclone with `git clone --recursive https://github.com/pgigioli/darknet_ros.git`
