### ISSUE TITLE
failed when using yolo.cfg  and yolo.weights

### ISSUE THREAD

**Issue by HolaMirai** [pgigioli/darknet_ros#2]
hi, pgigioli
I'm very sorry to bother you，when i use the yolo-tiny.cfg and yolo-tiny.weights ,the program works;but when i change to yolo.yolocfg and yolo.weights, error occurs .
  that is
`22: Convolutional Layer: 13 x 13 x 512 image, 1024 filters -> 13 x 13 x 1024 image`
`23: Convolutional Layer: 13 x 13 x 1024 image, 1024 filters -> 13 x 13 x 1024 image`
`24: Convolutional Layer: 13 x 13 x 1024 image, 1024 filters -> 13 x 13 x 1024 image`
`25: Route Layer: 16`
`26: Type not recognized: [reorg]`
`Unused field: 'stride = 2'`
`27: Route Layer: 26 24`
`28: Layer before convolutional layer must output image.: File exists`
`ROS_interface: /home/lile/catkin_ws/src/darknet_ros-master/src/utils.c:181: error: Assertion `0' failed.`
`Aborted (core dumped)`

and i can't work it out ,can you help me ?
thank you your time!

**Comment by pgigioli** [comment]
You are using the cfg file for yolo_v2.  darknet_ros is only compatible with yolo_v1 for now.
