### ISSUE TITLE
Can't find bbox_array.h and bbox.h

### ISSUE THREAD

**Issue by Kn15263ss** [pgigioli/darknet_ros#4]
Hi~ I am having a bit of a problem~
when i catkin_make, it have a problem about "fatal error: darknet_ros/bbox_array.h: No such file or directory
 #include <darknet_ros/bbox_array.h>"

It may the darknet_ros folder don't have bbox_array.h and bbox.h file?

Thanks you~

**Comment by pgigioli** [comment]
ROS will generate those header files automatically when creating the msg files.  I just tested it and it should work.  Try adding 
`add_dependencies(ROS_interface my_package_generate_messages_cpp)`
`add_dependencies(yolo_object_detector my_package_generate_messages_cpp)`
at the bottom of your CMakelists.txt and try again.

**Comment by Kn15263ss** [comment]
sorry~ i have a another problem about use catkin_make.
The problem is 

![screenshot from 2017-08-03 18 02 53](https://user-images.githubusercontent.com/22387638/28916807-08a20532-7876-11e7-986d-7fbf09b3aaa2.png)

How do i fix this question? 
Thank you!

**Comment by pgigioli** [comment]
Your catkin_make is unable to find your cuda libraries.  Make sure you have set your LD_LIBRARY_PATH appropriately.  It should be:
`LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH`
or /usr/local/cuda/lib depending on your cuda version.

**Comment by Kn15263ss** [comment]
Thanks!  I have solved this problem when i use: sudo ln -s /usr/local/cuda/lib64/libcurand.so /usr/lib/libcurand.so

but...when i execute "rosrun darknet_ros yolo_object_detector"
Theu have some error like this:
![image](https://user-images.githubusercontent.com/22387638/28935560-85f33308-78b7-11e7-94e0-9f2f7735ae57.png)

I don't know what happen about this..
Thanks you!

**Comment by pgigioli** [comment]
It looks like you are trying to use the weights/cfg file from YOLOv2.  Unfortunately, I'm still working on updating this code to v2 but for now you can use the weights and cfg files from v1.  Check out the v1 site here: https://pjreddie.com/darknet/yolov1/.  You should be able to download the v1 weights from here: http://pjreddie.com/media/files/tiny-yolo.weights
