### ISSUE TITLE
Error with CUDA

### ISSUE THREAD

**Issue by wang19950602** [pgigioli/darknet_ros#5]
Hello, I have got a little problem when I catkin_make, 
![error with cuda](https://user-images.githubusercontent.com/32090473/30773058-6a166810-a09b-11e7-8a2f-dacefbfcecfa.png)
I got 2 GPU in my sever, GTX960 and Tesla K40, it seems that the darknet_ros node choose the GTX960 as default GPU, how can I change to Tesla K40. Just like in yolo, I can change gpu by adding option "-i 1".
Thank you!

**Comment by pgigioli** [comment]
There isn't a functional way of changing the GPU device but you can manually change the gpu_index param in 'cuda.c'

**Comment by wang19950602** [comment]
Much appreciate for your quick reply. Actually, the problem is not the choice of gpu device, I change the 'compute_30，sm_30' to 52 in CMakeFile.txt, which is the corresponding compute ability of GTX960, and finally it works!
