### ISSUE TITLE
Error with bbox coordinates

### ISSUE THREAD

**Issue by wang19950602** [pgigioli/darknet_ros#6]
Hello, I got a little problem using darknet_ros, I have changed the cfg and weights path to my own file, the node can detect target object, but the bbox coordinates are 0, shown in the following picture:
![found_object](https://user-images.githubusercontent.com/32090473/31323542-d5905df2-acdb-11e7-967e-4b2a1ffdf211.png)

![bbox coordinates error](https://user-images.githubusercontent.com/32090473/31323528-98e8a3a0-acdb-11e7-8126-2ba014b1859e.png)
I have test my cfg and weights file in yolo and the result is good.
May I ask you how to solve this problem? 
Thank you!

**Comment by pgigioli** [comment]
Can you try testing your cfg and weights file with the ROS_interface node?  Also, did you change the topic name to match your camera in lines 37-39 in YOLO_object_detector.cpp?

**Comment by pgigioli** [comment]
I've updated this repo to YOLO V2 and any bugs should be fixed.  I also included a Dockerfile that you can use to isolate any configuration bugs.  You can reclone the latest version with 
`git clone --recursive https://github.com/pgigioli/darknet_ros.git`

**Comment by davidsanchezf** [comment]
Good morning, I am having exactly the same issue, Can I ask how to solve it? I have cloned the git just a few weeks ago. Thanks so much in advance for your help, 

David

**Comment by pgigioli** [comment]
Are you using the usb_cam package for your camera node?  If not, there could be an issue with scaling the bbox coordinates.  It looks like objects are properly being detected and that the bbox just isnt being drawn correctly. 

In src/yolo_ros.cpp, lines 40-41 define the ros params for the camera width/height.  If you're not using usb_cam, you'll have to change those two lines to your correct ros params defining the camera width/height (they should appear when you run "rosparam list").  If these params don't exist, you can manually set the camera width/height by deleting lines 216-217 and setting the FRAME_W and FRAME_H in lines 43-44 directly to your values.

**Comment by davidsanchezf** [comment]
Dear, sorry for disturbing you again.

I have already fixed it. I was mistaking in the way I was calling to height and width parameters. The camera node (dron_camera) comes from C++, but the topic comes from python. creating both parameters in python was enough. 

It works more than fine!!

Again, thanks so much for your help, time and for your work!! 

David

**Comment by pgigioli** [comment]
I'm glad it works!

**Comment by davidsanchezf** [comment]
It does!!! Great work!!!

Long live ROS!!!
